apiVersion: v2
name: bankeros
description: BankerOS — Open Source Digital Banking Platform Helm chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords: [banking, fintech, microservices, fastify, prisma]
home: https://github.com/bankeros/bankeros
maintainers:
  - name: BankerOS Team

dependencies:
  - name: postgresql
    version: "14.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: "26.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
